name: datapod_engine
description: Core execution engine for Datapod ORM.
version: 0.2.0
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
topics:
  - orm
  - database
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  datapod_api: ^0.2.0
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4

dependency_overrides:
  datapod_api:
    path: ../datapod_api
