name: datapod_engine
description: Core execution engine and plugin framework for the Datapod ORM.
version: 0.1.0
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
topics:
  - orm
  - database
  - persistence
  - engine
  - dart
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  datapod_api:
    path: ../datapod_api
  datapod_core:
    path: ../datapod_core
  meta: ^1.11.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
