name: datapod_mysql
description: MySQL plugin for Datapod ORM.
version: 0.2.1
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
topics:
  - orm
  - database
  - mysql
environment:
  sdk: ^3.10.0

dependencies:
  datapod_api: ^0.2.0
  datapod_engine: ^0.2.0
  mysql1: ^0.20.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0


