name: datapod_sqlite
description: SQLite plugin for Datapod ORM.
version: 0.2.0
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
topics:
  - orm
  - database
  - sqlite
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  datapod_api: ^0.2.0
  datapod_engine: ^0.2.0
  sqlite3: ^2.0.0
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  datapod_api:
    path: ../datapod_api
  datapod_engine:
    path: ../datapod_engine
