name: datapod_generator
description: Code generation logic for the Datapod ORM framework.
version: 0.1.0
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  datapod_api:
    path: ../datapod_api
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  meta: ^1.11.0
  yaml: ^3.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  build_test: ^2.2.0
