name: datapod_generator
description: Code generator for Datapod ORM.
version: 0.2.0
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
topics:
  - orm
  - database
  - codegen
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  code_builder: ^4.10.0
  datapod_api: ^0.2.0
  datapod_engine: ^0.2.0
  glob: ^2.1.0
  path: ^1.9.0
  source_gen: ^1.5.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  datapod_api:
    path: ../datapod_api
  datapod_engine:
    path: ../datapod_engine
