name: datapod_example
description: Example project for Datapod ORM.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  datapod_api:
    path: ../datapod_api
  datapod_postgres:
    path: ../datapod_postgres
  datapod_mysql:
    path: ../datapod_mysql
  datapod_sqlite:
    path: ../datapod_sqlite
  datapod_engine:
    path: ../datapod_engine
  meta: ^1.11.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.8
  datapod_generator:
    path: ../datapod_generator
  test: ^1.24.0
  lints: ^3.0.0

dependency_overrides:
  datapod_api:
    path: ../datapod_api
  datapod_engine:
    path: ../datapod_engine
  datapod_postgres:
    path: ../datapod_postgres
  datapod_mysql:
    path: ../datapod_mysql
  datapod_sqlite:
    path: ../datapod_sqlite
  datapod_generator:
    path: ../datapod_generator
