name: datapod_api
description: Core annotations and base interfaces for the Datapod ORM framework.
version: 0.2.1
homepage: https://github.com/cannon-fodder/dart_datapod
repository: https://github.com/cannon-fodder/dart_datapod
issue_tracker: https://github.com/cannon-fodder/dart_datapod/issues
topics:
  - orm
  - database
  - persistence
  - annotations
  - dart
environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.12.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
